[package]
name = "bomberman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.20.2"
itertools = "0.10.3"
rand = "0.8.4"

[profile.bench]
debug = true
